### PR TITLE
Eitot carbon

### PR DESCRIPTION
**Pull request by josh64x2**
OK here are my fixes for #776

The only problem is that when you build the project, git detects the `.helpindex` files have changed. Do you think adding them to `.gitignore` is the best approach? 

Previously the .helpindex files were only copied within the .app bundle and so git didn't detect them.

Technically they are a build artefact and so don't need to be in git.
Once this has been tested I'll delete all of the old `Vienna Help` directories before we merge.

### CODE REVIEW

**Comment by Eitot** [comment]
I think we should ignore any files that are automatically generated.

**Comment by josh64x2** [comment]
I just tested in 10.8 and the help files load 😄 (well, the 🇬🇧 ones do anyway).

**Comment by josh64x2** [comment]
OK it should be good to go if you want to give it a quick test with a lang other than French or English. (Might be a good idea later to add the languages that haven't been translated e.g. japanese, korean, to a "translation help wanted" post on the website).

**Comment by Eitot** [comment]
I think I found the problem. `CFBundleHelpBookName` is supposed to be a bundle identifier, not a name. 😑 That should fix it.

I will rename Vienna.help into Vienna Help and add it as a separate Xcode bundle target instead. Then we can let Xcode generate the help bundle automatically, while using its localisation features.

**Comment by josh64x2** [comment]
Oh I saw that note about `CFBundleHelpBookName` as well, except it doesn't work - Apple's instructions are wrong (as mentioned here https://alastairs-place.net/blog/2015/01/14/apple-help-in-2015/) and I couldn't get my`Vienna.help` to work until I just used a name and not a bundle identifier.

**Comment by josh64x2** [comment]
relevant quote:
>The second thing to note is that in spite of the documentation implying that you can use your help bundle identifier to refer to your help bundle (which would, admittedly, make sense), you can’t. You need to use the HPDBookTitle value.

**Comment by Eitot** [comment]
For me it is the opposite, now the link in preferences doesn’t work anymore. 😂

**Comment by Eitot** [comment]
This is so bizarre. When I build your PR, it doesn’t work. When I change `CFBundleHelpBookName` to the identifier, then it does. I wonder if there is some caching involved here that causes this.

**Comment by josh64x2** [comment]
Haha yeah maybe delete DerivedData and try?

**Comment by Eitot** [comment]
Nope. ☹️

**Comment by josh64x2** [comment]
It must be a build issue because when I copied the .app bundle to my mountain lion VM it worked...

Have you tried a clean git checkout into a different directory?

**Comment by Eitot** [comment]
Yep, no difference. I’ll try it in a VM as well.

**Comment by Eitot** [comment]
I have tested two deployment versions on ML and Mavericks and they both work. However, I also noticed that there is caching. I changed the font in the style sheet of one of them and the help viewer does not show it, it will keep the first style sheet instead. After a while, it is refreshed.

I think the problem may be located there. My theory is that the system indexes the help book separately and does not do this properly when there are multiple versions of the same program installed. The good news is that the bundle name now also works on Sierra.

**Pull request merged**
